const InstituteNames = [
  "IIT Bombay",
  "IIT Delhi",
  "IIT Kharagpur",
  "IIT Madras",
  "IIT Kanpur",
  "IIT Roorkee",
  "IIT Guwahati",
  "IIT Hyderabad",
  "IIT Patna",
  "IIT (ISM) Dhanbad",
  "IIT Bhubaneswar",
  "IIT Gandhinagar",
  "IIT Ropar",
  "IIT Indore",
  "IIT Mandi",
  "IIT Jodhpur",
  "IIT Tirupati",
  "IIT Palakkad",
  "IIT Dharwad",
  "IIT Bhilai",
  "IIT Goa",
  "IIT Jammu",
  "IIIT Pune",
  "IIIT Delhi",
  "IIIT Hyderabad",
  "IIIT Bangalore",
  "IIIT Allahabad",
  "IIIT Bhubaneswar",
  "IIIT Vadodara",
  "IIIT Kota",
  "IIIT Guwahati",
  "NIT Trichy",
  "NIT Warangal",
  "NIT Surathkal",
  "NIT Calicut",
  "NIT Rourkela",
  "NIT Kurukshetra",
  "NIT Durgapur",
  "NIT Jamshedpur",
  "NIT Silchar",
  "NIT Srinagar",
  "NIT Hamirpur",
  "NIT Agartala",
  "NIT Meghalaya",
  "NIT Nagaland",
  "NIT Manipur",
  "NIT Mizoram",
  "BITS Pilani",
  "BITS Goa",
  "BITS Hyderabad",
  "ISM Dhanbad",
  "IISc Bangalore",
  "IIM Ahmedabad",
  "IIM Bangalore",
  "IIM Calcutta",
  "IIM Lucknow",
  "IIM Indore",
  "IIM Kozhikode",
  "IIM Shillong",
  "IIM Rohtak",
  "IIM Trichy",
  "IIM Udaipur",
  "IIM Kashipur",
  "IIM Ranchi",
  "IIM Nagpur",
  "IIM Amritsar",
  "IIM Bodh Gaya",
  "IIM Jammu",
  "IIM Sambalpur",
  "IIM Sirmaur",
  "IIM Visakhapatnam",
  "IISER Pune",
  "IISER Kolkata",
  "IISER Mohali",
  "IISER Bhopal",
  "IISER Thiruvananthapuram",
  "IISER Tirupati",
  "IISER Berhampur",
  "IISER Nagaland",
  "IISER Jammu",
  "IISER Gandhinagar",
  "IISER Bhubaneswar",
  "IISER Tirupati",
  "IISER Kochi",
  "IISER Visakhapatnam",
  "IISER Pune",
  "IISER Kolkata",
  "IISER Mohali",
  "IISER Bhopal",
  "IISER Thiruvananthapuram",
  "IISER Tirupati",
  "IISER Berhampur",
  "IISER Nagaland",
  "IISER Jammu",
  "IISER Gandhinagar",
  "IISER Bhubaneswar",
  "IISER Tirupati",
  "IISER Kochi",
  "IISER Visakhapatnam",
  "IIFT Delhi",
  "IIFT Kolkata",
];
const TopicNames = [
  "Data Scientist",
  "Cybersecurity Analyst",
  "Full Stack Developer",
  "UI/UX Designer",
  "Cloud Architect",
  "DevOps Engineer",
  "Machine Learning Engineer",
  "Mobile App Developer",
  "Frontend Developer",
  "Backend Developer",
  "Software Engineer",
  "Network Administrator",
  "Database Administrator",
  "System Administrator",
  "Blockchain Developer",
  "Game Developer",
  "IT Project Manager",
  "Business Analyst",
  "Quality Assurance Engineer",
  "Embedded Systems Engineer",
  "Web Designer",
  "Data Analyst",
  "AI Engineer",
  "Robotics Engineer",
  "Digital Marketing Specialist",
  "SEO Specialist",
  "Social Media Manager",
  "Content Creator",
  "Graphic Designer",
  "Video Editor",
  "Sales Representative",
  "Financial Analyst",
  "HR Manager",
  "Customer Support Specialist",
  "Technical Writer",
  "IT Consultant",
  "Product Manager",
  "Scrum Master",
  "Agile Coach",
  "IT Trainer",
  "Network Engineer",
  "IT Security Specialist",
  "Cloud Developer",
  "Data Engineer",
  "Software Architect",
  "Systems Analyst",
  "IT Auditor",
  "IT Risk Manager",
  "Project Coordinator",
  "Business Intelligence Analyst",
];
export { InstituteNames, TopicNames };
